config/routes.rb
Socialpro::Application.routes.draw do
  devise_for :users
  root :to => 'home#index'
  match '/display_tweets'=>'Reviews#display_tweets', :as=>:filter_submit
	get '/filters' => 'Reviews#filter'
#	post '/filter_submit' => 'Reviews#filter_submit', :as => :filter_submit
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :terms
  # attr_accessible :title, :body
	validates :terms, acceptance: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
	before_filter :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	require 'twitter'
	before_filter :authenticate_user!, :except => ['index']
  def index
  end

	def display_tweets
	
@tweets = $client.search("#timesofindia", :lang => "en", :result_type => "recent").take(3)
#raise @tweets.inspect

	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def filter
	end
	
	def display_tweets
		text_for_reviews_search = params[:make]+' '+params[:model]+' '+params[:version]
		p text_for_reviews_search.inspect
		session['text_for_reviews_search'] = text_for_reviews_search
		since_date = params[:date][:year]+'-'+params[:date][:month]+'-'+params[:date][:day]
		p since_date
		
		@tweets = $client.search("#{text_for_reviews_search}", :lang => "en", :result_type => "recent", :since=> since_date).take(200)	
	end

	def display_fb_posts
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/home/index.html.erb
<div class="jumbotron">
  <% if user_signed_in? %>
    <h1>Welcome back, trusted user!</h1>
    <p class="lead">
     <%= link_to 'Dispaly Tweets', '/display_tweets'%>
    </p>
  <% else %>
    <h1>Welcome, new user!</h1>
    <p class="lead">
      You must sign in or sign up before you can access our super sweet,
      top secret content.
    </p>
    <div class="row-fluid">
      <div class="span6">
        <%= link_to "Sign In", new_user_session_path, :class => "btn btn-success" %>
      </div>
      <div class="span6">
        <%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title><%= content_for?(:title) ? yield(:title) : "Socialpro" %></title>
    <%= javascript_include_tag "jquery-1.4.2.min", "rails", "highcharts" %>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

		<div class="container-narrow">
<%= bootstrap_flash %>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="/">SocialPro</a>
<ul class="nav nav-pills pull-right">
<% if user_signed_in? %>
<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'btn btn-large btn-danger' %></li>
</ul>
      <ul class="nav">
        <li class="active"><a href="/">Dashboard</a></li>
        <li><a href="/facebook_reviews">FaceBook</a></li>
	<li><a href="/display_tweets">Twitter</a></li>
	<li><a href="/filters">Filter</a></li>
      </ul>
<% else %>
    
      <ul class="nav pull-right">
        <li><%= link_to "Sign in", new_user_session_path %></li>
    <li><%= link_to "Sign up", new_user_registration_path %></li>
      </ul>
<% end %>
    </div>
  </div>
</div>


  <%= yield %>
</div>


  </body>

<script type="text/javascript">
$(document).ready(function () {
$('ul.nav li').removeClass('active');
        $('a[href="' + this.location.pathname + '"]').parent().addClass('active');
    });
</script>

</html>

app/views/reviews/display_tweets.html.erb
<div id="graph-container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>


<script type="text/javascript">
$(function () {
    $('#graph-container').highcharts({
        title: {
            text: 'Monthly Average Temperature',
            x: -20 //center
        },
        subtitle: {
            text: 'Source: WorldClimate.com',
            x: -20
        },
        xAxis: {
            categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        },
        yAxis: {
            title: {
                text: 'Temperature (°C)'
            },
            plotLines: [{
                value: 0,
                width: 1,
                color: '#808080'
            }]
        },
        tooltip: {
            valueSuffix: '°C'
        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle',
            borderWidth: 0
        },
        series: [{
            name: 'Tokyo',
            data: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
        }, {
            name: 'New York',
            data: [-0.2, 0.8, 5.7, 11.3, 17.0, 22.0, 24.8, 24.1, 20.1, 14.1, 8.6, 2.5]
        }, {
            name: 'Berlin',
            data: [-0.9, 0.6, 3.5, 8.4, 13.5, 17.0, 18.6, 17.9, 14.3, 9.0, 3.9, 1.0]
        }, {
            name: 'London',
            data: [3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8]
        }]
    });
});
</script>


<div class="border-form-div">
<h3> Tweets from the twitter </h3>
<% @tweets.each do |tweet| %>
<%= tweet.inspect %>
			<%= "#{tweet.user.screen_name}: #{tweet.text}" %><br/><br/><br/><br/><br/>
		<% end %>
</div>

app/views/reviews/filter.html.erb
<div class="border-form-div">
<h1>Filters</h1>

<%= form_tag filter_submit_path, :method=> :post do %>
	<%= label_tag "Make" %>  
	<%= select_tag "make", options_for_select([['BMW' ,'BMW'], ['Audi', 'Audi'],['Honda','Honda'],['Hyundai','Hyundai'],['ICML','ICML'],['Ferrari','Ferrari'], ['Mini','Mini'], ['Skoda', 'Skoda'], ['Tata', 'Tata']]) %>
	<%= label_tag "Model" %>  
	<%= select_tag "model", options_for_select([['1 series' ,'1 series'],['A3','A3'], ['A4','A4'], ['3 Series', '3 Series'], ['458 Italia', '458 Italia'], ['Elantra', 'Elantra'], ['City', 'City'], ['Cooper', 'Cooper'], ['Rapid', 'Rapid'], ['Nano', 'Nano']]) %>
	<%= label_tag "Version" %>  
	<%= select_tag "version", options_for_select([['116i Hatchback' ,'116i Hatchback'], ['Audi A3 35TDI Attraction','Audi A3 35TDI Attraction'], ['320d', '320d'], ['Ferrari 458 Italia Coupe', 'Ferrari 458 Italia Coupe'], ['Honda City E', 'Honda City E'], ['Honda City S', 'Honda City S'], ['Honda City E', 'Honda City E'], ['Audi A4 2.0 TDI (143bhp)', 'Audi A4 2.0 TDI (143bhp)'],['Hyundai Elantra 1.8 S', 'Hyundai Elantra 1.8 S'], ['Hyundai Elantra 1.6 S', 'Hyundai Elantra 1.6 S'], ['Mini Cooper 1.6', 'Mini Cooper 1.6'], ['Skoda Rapid Active 1.6 MPI MT', 'Skoda Rapid Active 1.6 MPI MT'], ['Tata Nano CX', 'Tata Nano CX']]) %>
	</br>
	<%= select_date(date_since = Date.current, options = {}, html_options = {}) %><br>
	
<%= submit_tag "submit", :class=>'btn btn-primary' %>
<% end %>

<style>
select#date_day,select#date_month,select#date_year
{
	width:70px;
}
</style>

</div>